
### Create a new permission
POST http://localhost:3000/permission
Content-Type: application/json

{
    "name": "view-permission"
}



### fetch all permission
GET http://localhost:3000/permission
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjFjOGRjMGE4NjgyNmJkOGFjMTg4YmIiLCJpYXQiOjE2NDYxMTU3NDIsImV4cCI6MTY0NjEzMzc0Mn0.V8x17K4CkCFxP4z8OXKvOaD49RR-pQvO0n9-WcDfPPA



### Update a new permission
PATCH http://localhost:3000/permission/621c98802d4a5231b2fedc7f
Content-Type: application/json

{
    "name": "user"
}