### Create a new user
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "hi there",
    "email": "usertwo@gmail.com",
    "phone": "01903709156",
    "password": "password"
}


### login a new user
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "usertwo@gmail.com",
    "password": "password"
}

### fetch all user
GET http://localhost:3000/user



### Update a new user
PATCH http://localhost:3000/user/621c8dc0a86826bd8ac188bb
Content-Type: application/json

{
    "role": "621c98802d4a5231b2fedc7f"
}